### ISSUE TITLE
Feature request: Add VPN

### ISSUE THREAD

**Issue by vurtomatic** [vookimedlo/alfred-adapters#2]
Hi! I was wondering if you can add a functionality to toggle VPN?

I have a simple AppleScript right now that's triggered by a hotkey, and also have separate scripts for Wifi and Bluetooth. But since yours already has 2 out of 3 together, I thought I'd ask about adding VPN. (And yours is much better since it detects current states and has notification.)

Here's my basic VPN script I found on the internet for reference:

```
set vpn to "Corporate"

tell application "System Events"
	set rc to do shell script "scutil --nc status " & vpn
	if rc starts with "Connected" then
		do shell script "scutil --nc stop " & vpn
	else
		do shell script "scutil --nc start " & vpn
	end if
end tell
```

**Comment by vookimedlo** [comment]
Hi,

I use just the tunnelblick vpn and have a dedicated workflow for it - https://github.com/vookimedlo/alfred-vpn-tunnelblick.
Therefore I'm not going to add any VPN support to this workflow.

However, feel free to do a fork of this repo and add there whatever you need. Let the open-source live! ;)

Sorry.
